# Generated by Django 4.1.7 on 2023-03-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collection',
            new_name='collection_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
    ]
